name: Capstone Project CI worflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint_and_unit_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [18, 20]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: "npm"
          cache-dependency-path: package-lock.json,
      - name: Install dependencies
        run: npm ci
      - name: Run linting
        run: npm run lint
      - name: Run unit tests
        run: npm test
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
